import os
import requests
from datetime import datetime

def generate_audio_elevenlabs(script_text, voice='Bella'):
    try:
        with open(r'F:\AI_Oracle_Root\scarify\config\credentials\elevenlabs_api.key', 'rb') as f:
            raw_bytes = f.read()
        
        if raw_bytes.startswith(b'\xef\xbb\xbf'):
            clean_bytes = raw_bytes[3:]
        else:
            clean_bytes = raw_bytes
        
        api_key = clean_bytes.decode('utf-8').strip()
        print(f'✅ API key loaded: {api_key[:15]}...')
        
        url = 'https://api.elevenlabs.io/v1/text-to-speech/EXAVITQu4vr4xnSDxMaL'
        
        headers = {
            'Accept': 'audio/mpeg',
            'Content-Type': 'application/json',
            'xi-api-key': api_key
        }
        
        data = {
            'text': script_text,
            'model_id': 'eleven_monolingual_v1',
            'voice_settings': {
                'stability': 0.5,
                'similarity_boost': 0.5
            }
        }
        
        print('🎵 Calling ElevenLabs API...')
        response = requests.post(url, json=data, headers=headers)
        
        if response.status_code == 200:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            audio_filename = f'F:\\AI_Oracle_Root\\scarify\\output\\audio\\{voice}_{timestamp}.mp3'
            os.makedirs(os.path.dirname(audio_filename), exist_ok=True)
            
            with open(audio_filename, 'wb') as f:
                f.write(response.content)
            
            print(f'✅ REAL AUDIO GENERATED: {audio_filename}')
            print(f'✅ FILE SIZE: {len(response.content)} bytes')
            return audio_filename
        else:
            print(f'❌ API Error: {response.status_code}')
            print(f'🔧 Response: {response.text}')
            return None
            
    except Exception as e:
        print(f'❌ Audio generation failed: {e}')
        return None

script_content = 'This is real audio generated by the SCARIFY system. No placeholders, no bullshit. Actual AI-generated speech for YouTube content.'
print('🚀 TESTING ELEVENLABS API')
audio_file = generate_audio_elevenlabs(script_content)

if audio_file:
    print('\n🎉 SUCCESS: Real MP3 file created!')
    print(f'📍 Location: {audio_file}')
else:
    print('\n❌ Failed - check API key and connection')
