"""
VERIFY SYSTEM COMPLETE - No Placeholders, All Real
Checks for:
- Missing placeholders
- Empty functions
- Broken imports
- Missing directories
- Actual functionality
"""
import sys
from pathlib import Path

BASE = Path("F:/AI_Oracle_Root/scarify/abraham_horror")
errors = []
warnings = []

def check_file_completeness():
    """Check all Python files for placeholders"""
    files_to_check = [
        "ABRAHAM_COMEDY_YOUTUBE_COMPLETE.py",
        "ABRAHAM_PROFESSIONAL_UPGRADE.py",
        "CHAPMAN_2025_YOUTUBE_AUTO.py"
    ]
    
    placeholder_patterns = [
        "YOUR_API_KEY_HERE",
        "YOUR_IMAGE_API_ENDPOINT_HERE",
        "TODO:",
        "FIXME:",
        "PLACEHOLDER",
        "INSERT_HERE",
        "NotImplementedError",
        "raise NotImplemented",
    ]
    
    for filename in files_to_check:
        filepath = BASE / filename
        if not filepath.exists():
            errors.append(f"Missing file: {filename}")
            continue
        
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            lines = content.split('\n')
            
        for i, line in enumerate(lines, 1):
            for pattern in placeholder_patterns:
                if pattern in line and not line.strip().startswith('#'):
                    warnings.append(f"{filename}:{i} - Possible placeholder: {pattern}")
                    break
    
    return len(errors) == 0 and len(warnings) == 0

def check_directories():
    """Verify all directories exist and have purpose"""
    required_dirs = {
        "audio": "Audio files generated by ElevenLabs",
        "videos": "Final video output",
        "temp": "Temporary processing files",
        "images": "Lincoln portrait images",
        "scripts": "Generated scripts/logs",
        "youtube_ready": "Videos ready for YouTube",
        "uploaded": "Videos already uploaded"
    }
    
    for dir_name, purpose in required_dirs.items():
        dir_path = BASE / dir_name
        if not dir_path.exists():
            dir_path.mkdir(parents=True, exist_ok=True)
            warnings.append(f"Created missing directory: {dir_name}")
        elif not list(dir_path.iterdir()):
            warnings.append(f"Directory empty (but OK): {dir_name}")
    
    return True

def check_images():
    """Verify Lincoln images exist"""
    images_dir = BASE / "images"
    lincoln_images = list(images_dir.glob("*lincoln*.jpg")) + list(images_dir.glob("*lincoln*.png"))
    
    if not lincoln_images:
        warnings.append("No Lincoln images found - will use fallback (still works)")
    else:
        print(f"    [OK] Found {len(lincoln_images)} Lincoln image(s)")
    
    return True

def check_imports():
    """Test that all required modules can be imported"""
    required_modules = [
        "requests",
        "bs4",
        "moviepy",
        "PIL",
        "google.oauth2",
        "googleapiclient"
    ]
    
    for module_name in required_modules:
        try:
            __import__(module_name)
            print(f"    [OK] Module available: {module_name}")
        except ImportError as e:
            errors.append(f"Missing module: {module_name} - {e}")
    
    return len(errors) == 0

def check_api_keys():
    """Verify API keys are configured (without exposing them)"""
    try:
        from ABRAHAM_PROFESSIONAL_UPGRADE import ELEVENLABS_KEY, PEXELS_KEY
        
        if ELEVENLABS_KEY == "YOUR_KEY_HERE" or len(ELEVENLABS_KEY) < 20:
            errors.append("ELEVENLABS_KEY not configured properly")
        else:
            print("    [OK] ElevenLabs key configured")
        
        if PEXELS_KEY == "YOUR_KEY_HERE" or len(PEXELS_KEY) < 20:
            errors.append("PEXELS_KEY not configured properly")
        else:
            print("    [OK] Pexels key configured")
    except Exception as e:
        errors.append(f"Could not check API keys: {e}")
    
    return True

def check_core_functions():
    """Test that core functions exist and are callable"""
    try:
        sys.path.insert(0, str(BASE))
        
        # Check professional upgrade functions
        from ABRAHAM_PROFESSIONAL_UPGRADE import (
            scrape_current_headlines, generate_comedy_script,
            generate_male_voice, create_professional_video,
            upload_to_youtube, create_animated_bg
        )
        
        functions = [
            scrape_current_headlines, generate_comedy_script,
            generate_male_voice, create_professional_video,
            upload_to_youtube, create_animated_bg
        ]
        
        for func in functions:
            if not callable(func):
                errors.append(f"Function {func.__name__} not callable")
            else:
                print(f"    [OK] Function exists: {func.__name__}")
        
        return True
    except Exception as e:
        errors.append(f"Core function check failed: {e}")
        return False

if __name__ == "__main__":
    print("\n" + "="*70)
    print("VERIFYING SYSTEM COMPLETE - NO PLACEHOLDERS")
    print("="*70 + "\n")
    
    print("[1/6] Checking file completeness...")
    check_file_completeness()
    
    print("\n[2/6] Checking directories...")
    check_directories()
    
    print("\n[3/6] Checking images...")
    check_images()
    
    print("\n[4/6] Checking imports...")
    check_imports()
    
    print("\n[5/6] Checking API keys...")
    check_api_keys()
    
    print("\n[6/6] Checking core functions...")
    check_core_functions()
    
    print("\n" + "="*70)
    print("VERIFICATION RESULTS")
    print("="*70)
    
    if errors:
        print(f"\n[ERRORS] {len(errors)} critical issues found:")
        for e in errors:
            print(f"  - {e}")
    
    if warnings:
        print(f"\n[WARNINGS] {len(warnings)} non-critical issues:")
        for w in warnings:
            print(f"  - {w}")
    
    if not errors and not warnings:
        print("\n[SUCCESS] System is complete - no placeholders, all real!")
    elif not errors:
        print("\n[OK] System functional - some warnings but nothing critical")
    else:
        print("\n[FAIL] System has critical errors that must be fixed")
        sys.exit(1)
    
    print()


